name: NotResourcePack
version: '1.0'
main: not.notoffical.NotResourcePack
api-version: '1.16'

commands:
  notrp reload:
    description: Перезагрузка конфигурации плагина
    usage: /<command> reload
    permission: notrp.reload

permissions:
  notrp.reload:
    description: Право на перезагрузку конфигурации плагина
    default: op